SunsetDynamics = SunsetDynamics or {}

-- GTA Vehicle Class ID to Default Archetype mapping
SunsetDynamics.ClassToArchetype = {
    [0]  = 'compact_fwd',       -- Compacts
    [1]  = 'sedan_rwd',         -- Sedans
    [2]  = 'suv_awd',           -- SUVs
    [3]  = 'coupe_rwd',         -- Coupes
    [4]  = 'muscle_rwd',        -- Muscle
    [5]  = 'sports_rwd',        -- Sports Classics
    [6]  = 'sports_rwd',        -- Sports
    [7]  = 'super_awd',         -- Super
    [8]  = 'motorcycle_sport',  -- Motorcycles
    [9]  = 'offroad',           -- Off-road
    [10] = 'commercial_heavy',  -- Industrial
    [11] = 'van',               -- Utility
    [12] = 'van',               -- Vans
    [17] = 'sedan_rwd',         -- Service (Taxi, etc.)
    [18] = 'emergency_sedan',   -- Emergency
    [19] = 'offroad',           -- Military
    [20] = 'commercial_heavy',  -- Commercial
    [22] = 'sports_rwd',        -- Open Wheel
}

-- Canonical Archetype Baseline Handling Templates
SunsetDynamics.Archetypes = {
    ['compact_fwd'] = {
        category = 'compact',
        drivetrain = 'fwd',
        weightKg = 1150,
        handling = {
            fMass = 1150.0,
            fInitialDragCoeff = 8.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.05, z = -0.05 },
            vecInertiaMultiplier = { x = 1.0, y = 1.2, z = 1.2 },
            fDriveBiasFront = 1.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.19,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.8,
            fClutchChangeRateScaleDownShift = 1.8,
            fInitialDriveMaxFlatVel = 155.0,
            fBrakeForce = 0.65,
            fBrakeBiasFront = 0.65,
            fHandBrakeForce = 0.60,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.05,
            fTractionCurveMin = 1.85,
            fTractionCurveLateral = 22.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.1,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.52,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.1,
            fSuspensionCompDamp = 1.3,
            fSuspensionReboundDamp = 1.9,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.12,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.55,
            fAntiRollBarForce = 0.55,
            fAntiRollBarBiasFront = 0.58,
            fRollCentreHeightFront = 0.28,
            fRollCentreHeightRear = 0.30
        }
    },

    ['sedan_rwd'] = {
        category = 'sedan',
        drivetrain = 'rwd',
        weightKg = 1550,
        handling = {
            fMass = 1550.0,
            fInitialDragCoeff = 8.2,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.06 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.24,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.0,
            fClutchChangeRateScaleDownShift = 2.0,
            fInitialDriveMaxFlatVel = 195.0,
            fBrakeForce = 0.75,
            fBrakeBiasFront = 0.58,
            fHandBrakeForce = 0.70,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.15,
            fTractionCurveMin = 1.95,
            fTractionCurveLateral = 22.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.2,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.0,
            fSuspensionCompDamp = 1.4,
            fSuspensionReboundDamp = 2.2,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.70,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.30,
            fRollCentreHeightRear = 0.32
        }
    },

    ['sedan_awd'] = {
        category = 'sedan',
        drivetrain = 'awd',
        weightKg = 1620,
        handling = {
            fMass = 1620.0,
            fInitialDragCoeff = 8.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.06 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.40,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.26,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.2,
            fClutchChangeRateScaleDownShift = 2.2,
            fInitialDriveMaxFlatVel = 210.0,
            fBrakeForce = 0.80,
            fBrakeBiasFront = 0.56,
            fHandBrakeForce = 0.75,
            fSteeringLock = 37.0,
            fTractionCurveMax = 2.25,
            fTractionCurveMin = 2.05,
            fTractionCurveLateral = 22.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.0,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.1,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.3,
            fSuspensionUpperLimit = 0.09,
            fSuspensionLowerLimit = -0.12,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.80,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.30,
            fRollCentreHeightRear = 0.32
        }
    },

    ['sports_rwd'] = {
        category = 'sports',
        drivetrain = 'rwd',
        weightKg = 1420,
        handling = {
            fMass = 1420.0,
            fInitialDragCoeff = 7.2,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.08 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.4,
            fClutchChangeRateScaleDownShift = 2.4,
            fInitialDriveMaxFlatVel = 245.0,
            fBrakeForce = 0.95,
            fBrakeBiasFront = 0.60,
            fHandBrakeForce = 0.80,
            fSteeringLock = 37.0,
            fTractionCurveMax = 2.40,
            fTractionCurveMin = 2.15,
            fTractionCurveLateral = 23.0,
            fTractionSpringDeltaMax = 0.14,
            fLowSpeedTractionLossMult = 1.3,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.3,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.6,
            fSuspensionUpperLimit = 0.08,
            fSuspensionLowerLimit = -0.11,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.90,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.32,
            fRollCentreHeightRear = 0.34
        }
    },

    ['sports_awd'] = {
        category = 'sports',
        drivetrain = 'awd',
        weightKg = 1480,
        handling = {
            fMass = 1480.0,
            fInitialDragCoeff = 7.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.08 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.45,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.32,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.5,
            fClutchChangeRateScaleDownShift = 2.5,
            fInitialDriveMaxFlatVel = 250.0,
            fBrakeForce = 1.00,
            fBrakeBiasFront = 0.58,
            fHandBrakeForce = 0.85,
            fSteeringLock = 36.5,
            fTractionCurveMax = 2.50,
            fTractionCurveMin = 2.25,
            fTractionCurveLateral = 23.5,
            fTractionSpringDeltaMax = 0.14,
            fLowSpeedTractionLossMult = 1.0,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.7,
            fSuspensionReboundDamp = 2.7,
            fSuspensionUpperLimit = 0.08,
            fSuspensionLowerLimit = -0.11,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 1.00,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.32,
            fRollCentreHeightRear = 0.34
        }
    },

    ['super_rwd'] = {
        category = 'super',
        drivetrain = 'rwd',
        weightKg = 1350,
        handling = {
            fMass = 1350.0,
            fInitialDragCoeff = 6.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.3, z = 1.3 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.38,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 3.0,
            fClutchChangeRateScaleDownShift = 3.0,
            fInitialDriveMaxFlatVel = 285.0,
            fBrakeForce = 1.20,
            fBrakeBiasFront = 0.60,
            fHandBrakeForce = 0.90,
            fSteeringLock = 35.0,
            fTractionCurveMax = 2.65,
            fTractionCurveMin = 2.40,
            fTractionCurveLateral = 24.5,
            fTractionSpringDeltaMax = 0.13,
            fLowSpeedTractionLossMult = 1.2,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.8,
            fSuspensionCompDamp = 1.9,
            fSuspensionReboundDamp = 3.0,
            fSuspensionUpperLimit = 0.06,
            fSuspensionLowerLimit = -0.09,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 1.20,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.35,
            fRollCentreHeightRear = 0.36
        }
    },

    ['super_awd'] = {
        category = 'super',
        drivetrain = 'awd',
        weightKg = 1450,
        handling = {
            fMass = 1450.0,
            fInitialDragCoeff = 5.8,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.3, z = 1.3 },
            fDriveBiasFront = 0.40,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.40,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 3.2,
            fClutchChangeRateScaleDownShift = 3.2,
            fInitialDriveMaxFlatVel = 295.0,
            fBrakeForce = 1.25,
            fBrakeBiasFront = 0.58,
            fHandBrakeForce = 0.95,
            fSteeringLock = 35.0,
            fTractionCurveMax = 2.75,
            fTractionCurveMin = 2.50,
            fTractionCurveLateral = 25.0,
            fTractionSpringDeltaMax = 0.13,
            fLowSpeedTractionLossMult = 0.9,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.9,
            fSuspensionCompDamp = 2.0,
            fSuspensionReboundDamp = 3.1,
            fSuspensionUpperLimit = 0.06,
            fSuspensionLowerLimit = -0.09,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 1.30,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.35,
            fRollCentreHeightRear = 0.36
        }
    },

    ['muscle_rwd'] = {
        category = 'muscle',
        drivetrain = 'rwd',
        weightKg = 1650,
        handling = {
            fMass = 1650.0,
            fInitialDragCoeff = 7.8,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.05 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.32,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.9,
            fClutchChangeRateScaleDownShift = 1.9,
            fInitialDriveMaxFlatVel = 225.0,
            fBrakeForce = 0.72,
            fBrakeBiasFront = 0.62,
            fHandBrakeForce = 0.75,
            fSteeringLock = 37.0,
            fTractionCurveMax = 2.18,
            fTractionCurveMin = 1.85,
            fTractionCurveLateral = 21.0,
            fTractionSpringDeltaMax = 0.16,
            fLowSpeedTractionLossMult = 1.5,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.46,
            fTractionLossMult = 1.1,
            fSuspensionForce = 1.9,
            fSuspensionCompDamp = 1.2,
            fSuspensionReboundDamp = 2.0,
            fSuspensionUpperLimit = 0.12,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.65,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.30,
            fRollCentreHeightRear = 0.32
        }
    },

    ['suv_awd'] = {
        category = 'suv',
        drivetrain = 'awd',
        weightKg = 2300,
        handling = {
            fMass = 2300.0,
            fInitialDragCoeff = 9.8,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.02 },
            vecInertiaMultiplier = { x = 1.0, y = 1.6, z = 1.6 },
            fDriveBiasFront = 0.50,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.22,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.6,
            fClutchChangeRateScaleDownShift = 1.6,
            fInitialDriveMaxFlatVel = 185.0,
            fBrakeForce = 0.70,
            fBrakeBiasFront = 0.60,
            fHandBrakeForce = 0.65,
            fSteeringLock = 36.0,
            fTractionCurveMax = 2.10,
            fTractionCurveMin = 1.85,
            fTractionCurveLateral = 20.5,
            fTractionSpringDeltaMax = 0.18,
            fLowSpeedTractionLossMult = 1.0,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 1.9,
            fSuspensionCompDamp = 1.3,
            fSuspensionReboundDamp = 2.1,
            fSuspensionUpperLimit = 0.14,
            fSuspensionLowerLimit = -0.16,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.60,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.38,
            fRollCentreHeightRear = 0.40
        }
    },

    ['pickup_4x4'] = {
        category = 'pickup',
        drivetrain = 'awd',
        weightKg = 2450,
        handling = {
            fMass = 2450.0,
            fInitialDragCoeff = 10.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.05, z = 0.03 },
            vecInertiaMultiplier = { x = 1.0, y = 1.7, z = 1.7 },
            fDriveBiasFront = 0.40,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.21,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.5,
            fClutchChangeRateScaleDownShift = 1.5,
            fInitialDriveMaxFlatVel = 175.0,
            fBrakeForce = 0.68,
            fBrakeBiasFront = 0.65,
            fHandBrakeForce = 0.65,
            fSteeringLock = 35.0,
            fTractionCurveMax = 1.95,
            fTractionCurveMin = 1.75,
            fTractionCurveLateral = 19.5,
            fTractionSpringDeltaMax = 0.20,
            fLowSpeedTractionLossMult = 1.0,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.52,
            fTractionLossMult = 1.0,
            fSuspensionForce = 1.8,
            fSuspensionCompDamp = 1.2,
            fSuspensionReboundDamp = 2.0,
            fSuspensionUpperLimit = 0.16,
            fSuspensionLowerLimit = -0.18,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.52,
            fAntiRollBarForce = 0.50,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.42,
            fRollCentreHeightRear = 0.45
        }
    },

    ['offroad'] = {
        category = 'offroad',
        drivetrain = 'awd',
        weightKg = 1950,
        handling = {
            fMass = 1950.0,
            fInitialDragCoeff = 11.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.04 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.50,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.24,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.6,
            fClutchChangeRateScaleDownShift = 1.6,
            fInitialDriveMaxFlatVel = 160.0,
            fBrakeForce = 0.70,
            fBrakeBiasFront = 0.60,
            fHandBrakeForce = 0.70,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.10,
            fTractionCurveMin = 1.90,
            fTractionCurveLateral = 19.0,
            fTractionSpringDeltaMax = 0.22,
            fLowSpeedTractionLossMult = 0.9,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 0.9,
            fSuspensionForce = 1.7,
            fSuspensionCompDamp = 1.1,
            fSuspensionReboundDamp = 1.8,
            fSuspensionUpperLimit = 0.18,
            fSuspensionLowerLimit = -0.20,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.45,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.42,
            fRollCentreHeightRear = 0.44
        }
    },

    ['van'] = {
        category = 'van',
        drivetrain = 'rwd',
        weightKg = 2200,
        handling = {
            fMass = 2200.0,
            fInitialDragCoeff = 10.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.02 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.18,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.4,
            fClutchChangeRateScaleDownShift = 1.4,
            fInitialDriveMaxFlatVel = 150.0,
            fBrakeForce = 0.60,
            fBrakeBiasFront = 0.65,
            fHandBrakeForce = 0.55,
            fSteeringLock = 35.0,
            fTractionCurveMax = 1.90,
            fTractionCurveMin = 1.70,
            fTractionCurveLateral = 20.0,
            fTractionSpringDeltaMax = 0.16,
            fLowSpeedTractionLossMult = 1.1,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.52,
            fTractionLossMult = 1.0,
            fSuspensionForce = 1.9,
            fSuspensionCompDamp = 1.2,
            fSuspensionReboundDamp = 1.9,
            fSuspensionUpperLimit = 0.12,
            fSuspensionLowerLimit = -0.15,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.52,
            fAntiRollBarForce = 0.55,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.36,
            fRollCentreHeightRear = 0.38
        }
    },

    ['motorcycle_sport'] = {
        category = 'motorcycle',
        drivetrain = 'rwd',
        weightKg = 210,
        handling = {
            fMass = 210.0,
            fInitialDragCoeff = 5.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.05, z = -0.05 },
            vecInertiaMultiplier = { x = 1.0, y = 1.0, z = 1.0 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.42,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 3.5,
            fClutchChangeRateScaleDownShift = 3.5,
            fInitialDriveMaxFlatVel = 260.0,
            fBrakeForce = 1.10,
            fBrakeBiasFront = 0.70,
            fHandBrakeForce = 0.80,
            fSteeringLock = 35.0,
            fTractionCurveMax = 2.45,
            fTractionCurveMin = 2.20,
            fTractionCurveLateral = 20.0,
            fTractionSpringDeltaMax = 0.12,
            fLowSpeedTractionLossMult = 1.1,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 3.2,
            fSuspensionCompDamp = 2.0,
            fSuspensionReboundDamp = 3.0,
            fSuspensionUpperLimit = 0.08,
            fSuspensionLowerLimit = -0.10,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.0,
            fAntiRollBarBiasFront = 0.0,
            fRollCentreHeightFront = 0.20,
            fRollCentreHeightRear = 0.20
        }
    },

    ['emergency_sedan'] = {
        category = 'emergency',
        drivetrain = 'rwd',
        weightKg = 1680,
        handling = {
            fMass = 1680.0,
            fInitialDragCoeff = 7.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.09 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.32,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.2,
            fClutchChangeRateScaleDownShift = 2.2,
            fInitialDriveMaxFlatVel = 230.0,
            fBrakeForce = 0.95,
            fBrakeBiasFront = 0.55,
            fHandBrakeForce = 0.75,
            fSteeringLock = 39.0,
            fTractionCurveMax = 2.50,
            fTractionCurveMin = 2.30,
            fTractionCurveLateral = 22.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.1,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.5,
            fSuspensionUpperLimit = 0.09,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.90,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.32,
            fRollCentreHeightRear = 0.34
        }
    },

    ['emergency_suv'] = {
        category = 'emergency',
        drivetrain = 'awd',
        weightKg = 2250,
        handling = {
            fMass = 2250.0,
            fInitialDragCoeff = 8.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.04 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.45,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.30,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.0,
            fClutchChangeRateScaleDownShift = 2.0,
            fInitialDriveMaxFlatVel = 215.0,
            fBrakeForce = 0.90,
            fBrakeBiasFront = 0.58,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.40,
            fTractionCurveMin = 2.20,
            fTractionCurveLateral = 21.5,
            fTractionSpringDeltaMax = 0.16,
            fLowSpeedTractionLossMult = 1.0,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.1,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.4,
            fSuspensionUpperLimit = 0.12,
            fSuspensionLowerLimit = -0.15,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.85,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.36,
            fRollCentreHeightRear = 0.38
        }
    },

    ['commercial_heavy'] = {
        category = 'commercial',
        drivetrain = 'rwd',
        weightKg = 4500,
        handling = {
            fMass = 4500.0,
            fInitialDragCoeff = 14.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.8, z = 1.8 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.16,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 1.2,
            fClutchChangeRateScaleDownShift = 1.2,
            fInitialDriveMaxFlatVel = 125.0,
            fBrakeForce = 0.60,
            fBrakeBiasFront = 0.65,
            fHandBrakeForce = 0.50,
            fSteeringLock = 32.0,
            fTractionCurveMax = 1.80,
            fTractionCurveMin = 1.55,
            fTractionCurveLateral = 18.0,
            fTractionSpringDeltaMax = 0.22,
            fLowSpeedTractionLossMult = 1.0,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.52,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.2,
            fSuspensionUpperLimit = 0.15,
            fSuspensionLowerLimit = -0.18,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.55,
            fAntiRollBarForce = 0.60,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.45,
            fRollCentreHeightRear = 0.48
        }
    }
}
