--[[
    Sunset Vehicle Dynamics - Canonical Vehicle Archetypes
    Defines baseline physics profiles and fallback mappings by GTA vehicle class.
]]

SunsetVehicleDynamics = SunsetVehicleDynamics or {}

SunsetVehicleDynamics.Archetypes = {
    ['compact_fwd'] = {
        category = 'compact',
        drivetrain = 'fwd',
        weightKg = 1200,
        handling = {
            fMass = 1200.0,
            fInitialDragCoeff = 7.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.05 },
            vecInertiaMultiplier = { x = 1.0, y = 1.2, z = 1.2 },
            fDriveBiasFront = 1.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.24,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.0,
            fClutchChangeRateScaleDownShift = 2.0,
            fInitialDriveMaxFlatVel = 145.0,
            fBrakeForce = 0.70,
            fBrakeBiasFront = 0.60,
            fHandBrakeForce = 0.60,
            fSteeringLock = 39.0,
            fTractionCurveMax = 2.25,
            fTractionCurveMin = 2.05,
            fTractionCurveLateral = 21.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.05,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.54,
            fTractionLossMult = 1.0,
            fSuspensionForce = 1.9,
            fSuspensionCompDamp = 1.3,
            fSuspensionReboundDamp = 2.3,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.12,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.54,
            fAntiRollBarForce = 0.75,
            fAntiRollBarBiasFront = 0.60,
            fRollCentreHeightFront = 0.33,
            fRollCentreHeightRear = 0.34
        }
    },

    ['sedan_rwd'] = {
        category = 'sedan',
        drivetrain = 'rwd',
        weightKg = 1650,
        handling = {
            fMass = 1650.0,
            fInitialDragCoeff = 7.2,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.08 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.28,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.0,
            fClutchChangeRateScaleDownShift = 2.0,
            fInitialDriveMaxFlatVel = 160.0,
            fBrakeForce = 0.85,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.70,
            fSteeringLock = 38.5,
            fTractionCurveMax = 2.35,
            fTractionCurveMin = 2.15,
            fTractionCurveLateral = 22.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.20,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.1,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.6,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.90,
            fAntiRollBarBiasFront = 0.54,
            fRollCentreHeightFront = 0.34,
            fRollCentreHeightRear = 0.35
        }
    },

    ['sedan_awd'] = {
        category = 'sedan',
        drivetrain = 'awd',
        weightKg = 1750,
        handling = {
            fMass = 1750.0,
            fInitialDragCoeff = 7.1,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.09 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.40,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.30,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.1,
            fClutchChangeRateScaleDownShift = 2.1,
            fInitialDriveMaxFlatVel = 162.0,
            fBrakeForce = 0.90,
            fBrakeBiasFront = 0.54,
            fHandBrakeForce = 0.70,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.40,
            fTractionCurveMin = 2.20,
            fTractionCurveLateral = 22.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.10,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.7,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.52,
            fAntiRollBarForce = 0.95,
            fAntiRollBarBiasFront = 0.54,
            fRollCentreHeightFront = 0.34,
            fRollCentreHeightRear = 0.35
        }
    },

    ['sports_rwd'] = {
        category = 'sports',
        drivetrain = 'rwd',
        weightKg = 1480,
        handling = {
            fMass = 1480.0,
            fInitialDragCoeff = 6.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.34,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.3,
            fClutchChangeRateScaleDownShift = 2.3,
            fInitialDriveMaxFlatVel = 172.0,
            fBrakeForce = 1.00,
            fBrakeBiasFront = 0.52,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.52,
            fTractionCurveMin = 2.30,
            fTractionCurveLateral = 22.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.25,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.46,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.3,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.9,
            fSuspensionUpperLimit = 0.08,
            fSuspensionLowerLimit = -0.11,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 1.15,
            fAntiRollBarBiasFront = 0.52,
            fRollCentreHeightFront = 0.29,
            fRollCentreHeightRear = 0.31
        }
    },

    ['sports_awd'] = {
        category = 'sports',
        drivetrain = 'awd',
        weightKg = 1520,
        handling = {
            fMass = 1520.0,
            fInitialDragCoeff = 6.4,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.40,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.35,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.4,
            fClutchChangeRateScaleDownShift = 2.4,
            fInitialDriveMaxFlatVel = 174.0,
            fBrakeForce = 1.05,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.58,
            fTractionCurveMin = 2.38,
            fTractionCurveLateral = 23.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.10,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.49,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.7,
            fSuspensionReboundDamp = 3.0,
            fSuspensionUpperLimit = 0.08,
            fSuspensionLowerLimit = -0.11,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.52,
            fAntiRollBarForce = 1.25,
            fAntiRollBarBiasFront = 0.53,
            fRollCentreHeightFront = 0.28,
            fRollCentreHeightRear = 0.30
        }
    },

    ['super_rwd'] = {
        category = 'super',
        drivetrain = 'rwd',
        weightKg = 1380,
        handling = {
            fMass = 1380.0,
            fInitialDragCoeff = 5.9,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.13 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.38,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.8,
            fClutchChangeRateScaleDownShift = 2.8,
            fInitialDriveMaxFlatVel = 190.0,
            fBrakeForce = 1.18,
            fBrakeBiasFront = 0.52,
            fHandBrakeForce = 0.75,
            fSteeringLock = 37.0,
            fTractionCurveMax = 2.70,
            fTractionCurveMin = 2.48,
            fTractionCurveLateral = 24.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.20,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.45,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.6,
            fSuspensionCompDamp = 1.9,
            fSuspensionReboundDamp = 3.3,
            fSuspensionUpperLimit = 0.07,
            fSuspensionLowerLimit = -0.09,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.48,
            fAntiRollBarForce = 1.40,
            fAntiRollBarBiasFront = 0.52,
            fRollCentreHeightFront = 0.24,
            fRollCentreHeightRear = 0.25
        }
    },

    ['super_awd'] = {
        category = 'super',
        drivetrain = 'awd',
        weightKg = 1450,
        handling = {
            fMass = 1450.0,
            fInitialDragCoeff = 5.9,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.12 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.35,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.39,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.8,
            fClutchChangeRateScaleDownShift = 2.8,
            fInitialDriveMaxFlatVel = 192.0,
            fBrakeForce = 1.20,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.80,
            fSteeringLock = 37.0,
            fTractionCurveMax = 2.72,
            fTractionCurveMin = 2.52,
            fTractionCurveLateral = 24.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.12,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.7,
            fSuspensionCompDamp = 2.0,
            fSuspensionReboundDamp = 3.4,
            fSuspensionUpperLimit = 0.07,
            fSuspensionLowerLimit = -0.09,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 1.45,
            fAntiRollBarBiasFront = 0.53,
            fRollCentreHeightFront = 0.24,
            fRollCentreHeightRear = 0.25
        }
    },

    ['muscle_rwd'] = {
        category = 'muscle',
        drivetrain = 'rwd',
        weightKg = 1750,
        handling = {
            fMass = 1750.0,
            fInitialDragCoeff = 7.3,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.08 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1.05,
            fClutchChangeRateScaleUpShift = 2.0,
            fClutchChangeRateScaleDownShift = 2.0,
            fInitialDriveMaxFlatVel = 162.0,
            fBrakeForce = 0.88,
            fBrakeBiasFront = 0.54,
            fHandBrakeForce = 0.70,
            fSteeringLock = 38.0,
            fTractionCurveMax = 2.38,
            fTractionCurveMin = 2.12,
            fTractionCurveLateral = 21.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.40,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.46,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.1,
            fSuspensionCompDamp = 1.5,
            fSuspensionReboundDamp = 2.6,
            fSuspensionUpperLimit = 0.11,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.51,
            fAntiRollBarForce = 0.95,
            fAntiRollBarBiasFront = 0.54,
            fRollCentreHeightFront = 0.34,
            fRollCentreHeightRear = 0.35
        }
    },

    ['suv_awd'] = {
        category = 'suv',
        drivetrain = 'awd',
        weightKg = 2450,
        handling = {
            fMass = 2450.0,
            fInitialDragCoeff = 8.2,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.01 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.45,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.28,
            fDriveInertia = 1.1,
            fClutchChangeRateScaleUpShift = 1.8,
            fClutchChangeRateScaleDownShift = 1.8,
            fInitialDriveMaxFlatVel = 152.0,
            fBrakeForce = 0.80,
            fBrakeBiasFront = 0.56,
            fHandBrakeForce = 0.65,
            fSteeringLock = 36.5,
            fTractionCurveMax = 2.25,
            fTractionCurveMin = 2.00,
            fTractionCurveLateral = 20.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.10,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.3,
            fSuspensionCompDamp = 1.7,
            fSuspensionReboundDamp = 2.9,
            fSuspensionUpperLimit = 0.13,
            fSuspensionLowerLimit = -0.15,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.52,
            fAntiRollBarForce = 0.85,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.43,
            fRollCentreHeightRear = 0.44
        }
    },

    ['pickup_4x4'] = {
        category = 'pickup',
        drivetrain = 'awd',
        weightKg = 2600,
        handling = {
            fMass = 2600.0,
            fInitialDragCoeff = 8.5,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.03 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.45,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.27,
            fDriveInertia = 1.15,
            fClutchChangeRateScaleUpShift = 1.7,
            fClutchChangeRateScaleDownShift = 1.7,
            fInitialDriveMaxFlatVel = 145.0,
            fBrakeForce = 0.75,
            fBrakeBiasFront = 0.58,
            fHandBrakeForce = 0.65,
            fSteeringLock = 36.0,
            fTractionCurveMax = 2.20,
            fTractionCurveMin = 1.95,
            fTractionCurveLateral = 20.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.15,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.51,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.5,
            fSuspensionCompDamp = 1.8,
            fSuspensionReboundDamp = 3.1,
            fSuspensionUpperLimit = 0.15,
            fSuspensionLowerLimit = -0.17,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.53,
            fAntiRollBarForce = 0.80,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.46,
            fRollCentreHeightRear = 0.47
        }
    },

    ['offroad'] = {
        category = 'offroad',
        drivetrain = 'awd',
        weightKg = 2100,
        handling = {
            fMass = 2100.0,
            fInitialDragCoeff = 8.8,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.05 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.50,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.28,
            fDriveInertia = 1.1,
            fClutchChangeRateScaleUpShift = 1.8,
            fClutchChangeRateScaleDownShift = 1.8,
            fInitialDriveMaxFlatVel = 140.0,
            fBrakeForce = 0.72,
            fBrakeBiasFront = 0.55,
            fHandBrakeForce = 0.65,
            fSteeringLock = 37.0,
            fTractionCurveMax = 2.20,
            fTractionCurveMin = 1.95,
            fTractionCurveLateral = 19.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.10,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.3,
            fSuspensionCompDamp = 1.7,
            fSuspensionReboundDamp = 2.9,
            fSuspensionUpperLimit = 0.18,
            fSuspensionLowerLimit = -0.20,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.70,
            fAntiRollBarBiasFront = 0.52,
            fRollCentreHeightFront = 0.47,
            fRollCentreHeightRear = 0.48
        }
    },

    ['van'] = {
        category = 'van',
        drivetrain = 'rwd',
        weightKg = 2500,
        handling = {
            fMass = 2500.0,
            fInitialDragCoeff = 9.2,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.04 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.24,
            fDriveInertia = 1.1,
            fClutchChangeRateScaleUpShift = 1.6,
            fClutchChangeRateScaleDownShift = 1.6,
            fInitialDriveMaxFlatVel = 138.0,
            fBrakeForce = 0.70,
            fBrakeBiasFront = 0.58,
            fHandBrakeForce = 0.60,
            fSteeringLock = 36.0,
            fTractionCurveMax = 2.10,
            fTractionCurveMin = 1.85,
            fTractionCurveLateral = 19.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.10,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.52,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.8,
            fSuspensionReboundDamp = 3.0,
            fSuspensionUpperLimit = 0.12,
            fSuspensionLowerLimit = -0.14,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.54,
            fAntiRollBarForce = 0.75,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.45,
            fRollCentreHeightRear = 0.46
        }
    },

    ['motorcycle_sport'] = {
        category = 'motorcycle',
        drivetrain = 'rwd',
        weightKg = 230,
        handling = {
            fMass = 230.0,
            fInitialDragCoeff = 5.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.0 },
            vecInertiaMultiplier = { x = 1.0, y = 1.0, z = 1.0 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.42,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 3.0,
            fClutchChangeRateScaleDownShift = 3.0,
            fInitialDriveMaxFlatVel = 175.0,
            fBrakeForce = 1.10,
            fBrakeBiasFront = 0.65,
            fHandBrakeForce = 0.80,
            fSteeringLock = 35.0,
            fTractionCurveMax = 2.65,
            fTractionCurveMin = 2.40,
            fTractionCurveLateral = 22.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.15,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.6,
            fSuspensionCompDamp = 1.8,
            fSuspensionReboundDamp = 3.2,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.10,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.50,
            fAntiRollBarForce = 0.0,
            fAntiRollBarBiasFront = 0.0,
            fRollCentreHeightFront = 0.15,
            fRollCentreHeightRear = 0.15
        }
    },

    ['emergency_sedan'] = {
        category = 'emergency_sedan',
        drivetrain = 'rwd',
        weightKg = 1750,
        handling = {
            fMass = 1750.0,
            fInitialDragCoeff = 7.1,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = -0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.4, z = 1.4 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.34,
            fDriveInertia = 1.0,
            fClutchChangeRateScaleUpShift = 2.2,
            fClutchChangeRateScaleDownShift = 2.2,
            fInitialDriveMaxFlatVel = 168.0,
            fBrakeForce = 0.98,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38.5,
            fTractionCurveMax = 2.50,
            fTractionCurveMin = 2.30,
            fTractionCurveLateral = 22.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.18,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.48,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.1,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fSuspensionUpperLimit = 0.10,
            fSuspensionLowerLimit = -0.13,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.51,
            fAntiRollBarForce = 1.05,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.34,
            fRollCentreHeightRear = 0.35
        }
    },

    ['emergency_suv'] = {
        category = 'emergency_suv',
        drivetrain = 'awd',
        weightKg = 2650,
        handling = {
            fMass = 2650.0,
            fInitialDragCoeff = 8.2,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.01 },
            vecInertiaMultiplier = { x = 1.0, y = 1.5, z = 1.5 },
            fDriveBiasFront = 0.40,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1.1,
            fClutchChangeRateScaleUpShift = 2.0,
            fClutchChangeRateScaleDownShift = 2.0,
            fInitialDriveMaxFlatVel = 158.0,
            fBrakeForce = 0.90,
            fBrakeBiasFront = 0.55,
            fHandBrakeForce = 0.65,
            fSteeringLock = 36.5,
            fTractionCurveMax = 2.35,
            fTractionCurveMin = 2.10,
            fTractionCurveLateral = 21.0,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.12,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.50,
            fTractionLossMult = 1.0,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.8,
            fSuspensionReboundDamp = 3.0,
            fSuspensionUpperLimit = 0.13,
            fSuspensionLowerLimit = -0.15,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.53,
            fAntiRollBarForce = 0.95,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.44,
            fRollCentreHeightRear = 0.45
        }
    },

    ['commercial_heavy'] = {
        category = 'commercial',
        drivetrain = 'rwd',
        weightKg = 5500,
        handling = {
            fMass = 5500.0,
            fInitialDragCoeff = 12.0,
            vecCentreOfMassOffset = { x = 0.0, y = 0.0, z = 0.10 },
            vecInertiaMultiplier = { x = 1.0, y = 1.6, z = 1.6 },
            fDriveBiasFront = 0.0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.22,
            fDriveInertia = 1.4,
            fClutchChangeRateScaleUpShift = 1.4,
            fClutchChangeRateScaleDownShift = 1.4,
            fInitialDriveMaxFlatVel = 130.0,
            fBrakeForce = 0.65,
            fBrakeBiasFront = 0.60,
            fHandBrakeForce = 0.55,
            fSteeringLock = 33.0,
            fTractionCurveMax = 1.95,
            fTractionCurveMin = 1.70,
            fTractionCurveLateral = 18.5,
            fTractionSpringDeltaMax = 0.15,
            fLowSpeedTractionLossMult = 1.05,
            fCamberStiffnesss = 0.0,
            fTractionBiasFront = 0.54,
            fTractionLossMult = 1.0,
            fSuspensionForce = 3.0,
            fSuspensionCompDamp = 2.2,
            fSuspensionReboundDamp = 3.5,
            fSuspensionUpperLimit = 0.14,
            fSuspensionLowerLimit = -0.16,
            fSuspensionRaise = 0.0,
            fSuspensionBiasFront = 0.55,
            fAntiRollBarForce = 0.70,
            fAntiRollBarBiasFront = 0.55,
            fRollCentreHeightFront = 0.52,
            fRollCentreHeightRear = 0.53
        }
    }
}

-- Fallback mapping from GTA Vehicle Class ID to Archetype
SunsetVehicleDynamics.ClassToArchetype = {
    [0]  = 'compact_fwd',     -- Compacts
    [1]  = 'sedan_rwd',        -- Sedans
    [2]  = 'suv_awd',          -- SUVs
    [3]  = 'sports_rwd',       -- Coupes
    [4]  = 'muscle_rwd',       -- Muscle
    [5]  = 'sports_rwd',       -- Sports Classics
    [6]  = 'sports_rwd',       -- Sports
    [7]  = 'super_rwd',        -- Super
    [8]  = 'motorcycle_sport', -- Motorcycles
    [9]  = 'offroad',          -- Off-road
    [10] = 'commercial_heavy', -- Industrial
    [11] = 'van',              -- Utility
    [12] = 'van',              -- Vans
    [17] = 'van',              -- Service
    [18] = 'emergency_sedan',  -- Emergency
    [19] = 'commercial_heavy', -- Military
    [20] = 'commercial_heavy', -- Commercial
}
