--[[
    Sunset Vehicle Dynamics - Emergency & Police Vehicle Profiles
    Calibrated canonical handling profiles normalized from repository vehicles.meta and handling.meta.
]]

SunsetVehicleDynamics = SunsetVehicleDynamics or {}
SunsetVehicleDynamics.EmergencyProfiles = {
    ['police'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1750,
        handling = {
            fMass = 1750,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 160,
            fBrakeForce = 0.95,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 39,
            fTractionCurveMax = 2.45,
            fTractionCurveMin = 2.21,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['police2'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1800,
        handling = {
            fMass = 1800,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.36,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.05,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38.5,
            fTractionCurveMax = 2.55,
            fTractionCurveMin = 2.29,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['police3'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1820,
        handling = {
            fMass = 1820,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.45,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.35,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 168,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38,
            fTractionCurveMax = 2.5,
            fTractionCurveMin = 2.25,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['police4'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1720,
        handling = {
            fMass = 1720,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 162,
            fBrakeForce = 0.95,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 39,
            fTractionCurveMax = 2.45,
            fTractionCurveMin = 2.21,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['sheriff'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1760,
        handling = {
            fMass = 1760,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 160,
            fBrakeForce = 0.95,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 39,
            fTractionCurveMax = 2.45,
            fTractionCurveMin = 2.21,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['sheriff2'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'awd',
        weightKg = 2650,
        handling = {
            fMass = 2650,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0.4,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 155,
            fBrakeForce = 0.88,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 36,
            fTractionCurveMax = 2.3,
            fTractionCurveMin = 2.07,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['fbi'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1800,
        handling = {
            fMass = 1800,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.36,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.05,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38.5,
            fTractionCurveMax = 2.55,
            fTractionCurveMin = 2.29,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['fbi2'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'awd',
        weightKg = 2650,
        handling = {
            fMass = 2650,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0.4,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 155,
            fBrakeForce = 0.88,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 36,
            fTractionCurveMax = 2.3,
            fTractionCurveMin = 2.07,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['pranger'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'awd',
        weightKg = 2700,
        handling = {
            fMass = 2700,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0.45,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.3,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 150,
            fBrakeForce = 0.85,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 36,
            fTractionCurveMax = 2.25,
            fTractionCurveMin = 2.02,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['ambulance'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'rwd',
        weightKg = 2800,
        handling = {
            fMass = 2800,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.25,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 140,
            fBrakeForce = 0.72,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 35,
            fTractionCurveMax = 2.25,
            fTractionCurveMin = 2.02,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['firetruk'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'rwd',
        weightKg = 2800,
        handling = {
            fMass = 2800,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.26,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 145,
            fBrakeForce = 0.75,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 36,
            fTractionCurveMax = 2.25,
            fTractionCurveMin = 2.02,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['ballvmark'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.15,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 43,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['draftvmark'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1650,
        handling = {
            fMass = 1650,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['kurxmark'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1500,
        handling = {
            fMass = 1500,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.33,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 183,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.8,
            fTractionCurveMin = 2.6,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['parawmark'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'awd',
        weightKg = 2315,
        handling = {
            fMass = 2315,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0.5,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 159.5,
            fBrakeForce = 1.1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 40,
            fTractionCurveMax = 2.52,
            fTractionCurveMin = 2.35,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['tragambo'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.25,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 140,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.72,
            fTractionCurveMin = 2.5,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['tragmech'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.25,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 140,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.72,
            fTractionCurveMin = 2.5,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['tragpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.25,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 140,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.72,
            fTractionCurveMin = 2.5,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['briosoxpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1250,
        handling = {
            fMass = 1250,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.35,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 175,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.39,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['carrionmech'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1380,
        handling = {
            fMass = 1380,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 156,
            fBrakeForce = 0.85,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 40,
            fTractionCurveMax = 2.49,
            fTractionCurveMin = 2.25,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['carrionpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1380,
        handling = {
            fMass = 1380,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 156,
            fBrakeForce = 0.85,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 40,
            fTractionCurveMax = 2.49,
            fTractionCurveMin = 2.25,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['cazadorpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1380,
        handling = {
            fMass = 1380,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.31,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 176,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['clubrpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1540,
        handling = {
            fMass = 1540,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.35,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 180,
            fBrakeForce = 0.88,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 41,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.5,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['dawnpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1400,
        handling = {
            fMass = 1400,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.5,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 185,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['flashgrspd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1200,
        handling = {
            fMass = 1200,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.33,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 183,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.2,
            fTractionCurveMin = 2,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['hyctailpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1600,
        handling = {
            fMass = 1600,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.35,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 160,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['jubvenpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.15,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 43,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['omnvenpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1650,
        handling = {
            fMass = 1650,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['reblaxpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2185,
        handling = {
            fMass = 2185,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 8,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 180.5,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['rhinea19xpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1660,
        handling = {
            fMass = 1660,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 180,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['schlagpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1550,
        handling = {
            fMass = 1550,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.37,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 159.2,
            fBrakeForce = 0.8,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 38,
            fTractionCurveMax = 2.5,
            fTractionCurveMin = 2.3,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['shenronpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['sr8pd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['srhatpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1600,
        handling = {
            fMass = 1600,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.35,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 180,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.39,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['strcoupepd'] = {
        archetype = 'emergency_suv',
        category = 'police_suv',
        drivetrain = 'rwd',
        weightKg = 2315,
        handling = {
            fMass = 2315,
            fInitialDragCoeff = 8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = 0.01 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 159.5,
            fBrakeForce = 1.1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 40,
            fTractionCurveMax = 2.52,
            fTractionCurveMin = 2.35,
            fSuspensionForce = 2.4,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 0.9
        }
    },

    ['sultlpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 1100,
        handling = {
            fMass = 1100,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.5,
            nInitialDriveGears = 5,
            fInitialDriveForce = 0.33,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 145,
            fBrakeForce = 0.75,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 35,
            fTractionCurveMax = 2.5,
            fTractionCurveMin = 2.25,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['taurionpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 6,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 170,
            fBrakeForce = 1.2,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['tenfhycpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'rwd',
        weightKg = 1300,
        handling = {
            fMass = 1300,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 150,
            fBrakeForce = 1,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.6,
            fTractionCurveMin = 2.4,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    },

    ['xlsstrpd'] = {
        archetype = 'emergency_sedan',
        category = 'police_sedan',
        drivetrain = 'awd',
        weightKg = 2000,
        handling = {
            fMass = 2000,
            fInitialDragCoeff = 6.8,
            vecCentreOfMassOffset = { x = 0, y = 0, z = -0.09 },
            fDriveBiasFront = 0.3,
            nInitialDriveGears = 7,
            fInitialDriveForce = 0.4,
            fDriveInertia = 1,
            fInitialDriveMaxFlatVel = 160,
            fBrakeForce = 1.15,
            fBrakeBiasFront = 0.53,
            fHandBrakeForce = 0.75,
            fSteeringLock = 42,
            fTractionCurveMax = 2.72,
            fTractionCurveMin = 2.5,
            fSuspensionForce = 2.2,
            fSuspensionCompDamp = 1.6,
            fSuspensionReboundDamp = 2.8,
            fAntiRollBarForce = 1.15
        }
    }

}

SunsetVehicleDynamics.RegisterBatch(SunsetVehicleDynamics.EmergencyProfiles, 'emergency')
