Sunset = Sunset or {}

--- Static help catalog. Runtime filtering happens in sunset_help server.
Sunset.HelpAdminDescriptions = {
    kick = 'Kick a player from the server',
    ban = 'Permanently ban a player (player ID required)',
    unban = 'Remove a ban by player ID or license:xxx',
    tp = 'Teleport to a player or x y z coordinates',
    bring = 'Bring a player to your location',
    car = 'Spawn a vehicle by model name',
    dv = 'Delete your current vehicle',
    heal = 'Heal yourself or another player',
    revive = 'Revive a downed player',
    arespawn = 'Respawn a player at their saved spawn choice (home / HQ / default)',
    noclip = 'Toggle noclip mode',
    god = 'Toggle god mode',
    cc = 'Clear the chat for every player',
    anno = 'Trimite un anunt admin pe chat (rosu)',
    setadmin = 'Set admin level for an account',
    coords = 'Show your position — /coords, /getpos, /pos (add v4 for vector4). Tip: stand here, then /setcp [name]',
    dl = 'Toggle SA-MP-style vehicle debug labels: entity/net ID, model, plate, speed, health and network owner',
    hudexport = 'Export HUD layout JSON',
    setcp = 'Save your current position as a named checkpoint',
    delcp = 'Delete a saved admin checkpoint',
    gotocp = 'Teleport to a saved admin checkpoint by name',
    gotoloc = 'Teleport to a predefined world location by id or name',
    speed = 'Boost vehicle engine power while driving (multiplier)',
    dealershipadmin = 'Manage dealership stock, prices, availability and catalog entries',
    setjob = 'Set a player civilian job (trucker, fisherman, etc.)',
    setfaction = 'Assign a player to a faction with grade',
    givecar = 'Give a vehicle to a player (stored in garage)',
    giveitem = 'Give inventory items to a player: /giveitem [id] [item] [count]',
    givegun = 'Give a weapon to a player: /givegun [id] [weapon] [ammo]',
    setleader = 'Grant faction leader permissions to a member',
    removeleader = 'Revoke faction leader role from a member',
    spy = 'Toggle faction chat spy (/f, /r, /d) for moderators+',
    acreatehouse = 'Create a house at your current position: price, interior, minimum level, name',
    ahouseedit = 'Edit a house price, level, name, sale status, or enabled status',
    astats = 'Inspect an online player\'s character, economy and job progression',
    setstat = 'Set an online player stat: cash, bank, level, rp, rob, paydays, playtime, premium, hunger, thirst, stress',
    setsc = 'Set Blaze Points for a player: /setsc [id] [amount]',
    setpp = 'Alias for /setsc — set Blaze Points (premium points)',
    setrob = 'Set a player robbery points: /setrob [id] [value]',
    setjobstat = 'Set civilian job progress: /setjobstat [id] [job] [xp|level|tasks|earned] [value]',
    givelicense = 'Admin: grant a license: /givelicense [id] [driver|pilot|boat|weapon|hunting]',
    agivelicense = 'Admin: grant a license: /agivelicense [id] [driver|pilot|boat|weapon|hunting]',
    revokelicense = 'Revoke a license: /revokelicense [id] [driver|pilot|boat|weapon|hunting]',
    achecklicenses = 'Admin: view all licenses for a player character: /achecklicenses [player id]',
}

Sunset.HelpGeneralEntries = {
    { cmd = '/help', desc = 'Open this command guide' },
    { cmd = '/stats', desc = 'Open character statistics, level and Respect Point progress' },
    { cmd = '/buylevel', desc = 'Spend the required RP and money to purchase your next level' },
    { cmd = '/me [text]', desc = 'Roleplay action visible to nearby players' },
    { cmd = '/do [text]', desc = 'Describe the scene or environment' },
    { cmd = 'M', desc = 'Player menu — stats, vehicle, job, settings' },
    { cmd = 'I', desc = 'Inventory — select an item to use/drop it or choose a nearby player to trade' },
    { cmd = 'P', desc = 'Phone' },
    { cmd = 'Z', desc = 'Hold for player list' },
    { cmd = 'Z', desc = 'Cycle voice range — HUD shows mode + meters (e.g. Normal · 3.0m)' },
    { cmd = '/proximity [whisper|normal|shout]', desc = 'Set voice range directly' },
    { cmd = 'E', desc = 'Interact — shops, ATMs, faction HQ, crafting' },
    { cmd = 'G / /interact', desc = 'Context menu for a nearby player — civilian, faction and service actions' },
    { cmd = '/inventory', desc = 'Open inventory — dropped bags remain available for 5 minutes' },
    { cmd = '/accepttrade', desc = 'Accept the pending nearby inventory trade request' },
    { cmd = '/declinetrade', desc = 'Decline the pending inventory trade request' },
    { cmd = '/phone', desc = 'Toggle phone' },
    { cmd = '/documents', desc = 'View documents panel' },
    { cmd = '/id', desc = 'Show ID card' },
    { cmd = '/licenses', desc = 'Show licenses' },
    { cmd = '/issuelicense [id] [pilot|boat|weapon|hunting]', desc = 'On-duty LSSI instructor: authorize a nearby candidate at the correct exam facility' },
    { cmd = '/v', desc = 'Personal vehicles — spawn, GPS, park, or store' },
    { cmd = '/garage', desc = 'Garage panel' },
    { cmd = '/park', desc = 'While driving your personal vehicle, save its current world position' },
    { cmd = '[E] LS Customs', desc = 'In your vehicle at LS Customs HQ — repair ($250) or ECU tuning' },
    { cmd = '/dealership', desc = 'Browse vehicles at Premium Deluxe Motorsport' },
    { cmd = '2', desc = 'Start or stop the vehicle engine manually' },
    { cmd = 'U / /lock', desc = 'Lock or unlock your vehicle doors' },
    { cmd = 'K', desc = 'Toggle vehicle seatbelt' },
    { cmd = '/properties', desc = 'Browse houses, prices, owners, rent and access' },
    { cmd = '/sethome [id]', desc = 'Set spawn home at a house you own or rent' },
    { cmd = '/renthouse', desc = 'Explains how to rent; stand at a house and press E' },
    { cmd = '/unrent', desc = 'End your active house rental (job and faction stay)' },
    { cmd = '/houselock [id]', desc = 'Owner: lock or unlock your house' },
    { cmd = '/houserent [price|off] [id]', desc = 'Owner: accept renters and set payday rent' },
    { cmd = '/housemaxrenters [1-10] [id]', desc = 'Owner: set available rental slots' },
    { cmd = '/houseinterior [name] [id]', desc = 'Owner: change house interior' },
    { cmd = '/houseinteriors', desc = 'List available house interiors' },
    { cmd = '/hdescription [text|off]', desc = 'Owner: set the floating house message for renters and visitors' },
    { cmd = '/houserenters [id]', desc = 'Owner: list active renters' },
    { cmd = '/housekickrenter [character id] [house id]', desc = 'Owner: remove a renter' },
    { cmd = '/sellhouse [id] confirm', desc = 'Owner: sell house back for 70% of its price' },
    { cmd = '/emotes', desc = 'Open emotes panel' },
    { cmd = '/emote [name]', desc = 'Play an emote (sau /anim)' },
    { cmd = '/stopemote', desc = 'Stop current emote' },
    { cmd = '/handsup', desc = 'Raise hands' },
    { cmd = '/pass', desc = 'Open Blaze Pass rewards track' },
    { cmd = '/missions', desc = 'Open Blaze Pass missions' },
    { cmd = '/crafting', desc = 'Mark the nearest crafting station available to your faction' },
    { cmd = '/faction', desc = 'Faction rank, salary, and your commands' },
    { cmd = '/factions', desc = 'Browse factions and Discord/website application status' },
    { cmd = '/acceptfaction', desc = 'Accept a pending invitation from an admin-appointed faction leader' },
    { cmd = '/declinefaction', desc = 'Decline a pending faction invitation' },
    { cmd = '/leavefaction', desc = 'Leave your faction (job stays)' },
    { cmd = '/quitfaction', desc = 'Alias for /leavefaction (civilian job stays)' },
    { cmd = '/factionquit', desc = 'Alias for /leavefaction (civilian job stays)' },
    { cmd = '/quitgroup', desc = 'Alias for /leavefaction (civilian job stays)' },
    { cmd = '/duty', desc = 'Toggle on/off duty at faction HQ' },
    { cmd = '/clan', desc = 'Open your clan page — create, members, tag style, and management' },
    { cmd = '/group', desc = 'Same as /clan — clan unit panel' },
    { cmd = '/clans', desc = 'Browse all player-created clans on the server' },
    { cmd = '/c [message]', desc = 'Clan chat — only your clan members see it (shows rank + title)' },
    { cmd = '/cmotd [message?]', desc = 'Read clan MOTD; officers may set it' },
    { cmd = '/acceptclan', desc = 'Accept a pending clan invitation' },
    { cmd = '/declineclan', desc = 'Decline a pending clan invitation' },
    { cmd = '/f [message]', desc = 'Faction chat' },
    { cmd = '/fmotd [message?]', desc = 'Read faction MOTD; leaders may set it' },
    { cmd = '/r [message]', desc = 'Faction radio — LSPD, Sheriff, FIB, EMS, LSFD only (same faction)' },
    { cmd = '/d [message]', desc = 'Inter-agency department radio (LSPD, Sheriff, FIB, EMS, LSFD)' },
    { cmd = '/spy', desc = 'Admin: toggle spy on faction /f, /r, and /d traffic' },
    { cmd = '/service [type] [msg]', desc = 'Request taxi, medic, fire, or mechanic' },
    { cmd = '/relook', desc = 'Re-open character appearance editor' },
    { cmd = '/respawn', desc = 'Respawn at hospital when downed (after bleedout timer)' },
    { cmd = '/spawnmenu', desc = 'Open spawn location selector without reconnecting' },
    { cmd = '/hudedit', desc = 'Move HUD panels' },
    { cmd = '/hudreset', desc = 'Reset HUD layout to default' },
    { cmd = '/rob', desc = 'Start a marked luxury-store robbery (requires 1 rob point, a lockpick and enough on-duty police)' },
    { cmd = '[E] robbery', desc = 'Start robbery, route the security circuit, smash displays, then escape 300m' },
    { cmd = '[E] fence', desc = 'Sell stolen watches and jewelry to the dockside fence' },
}

--- Command usage for chat preflight (permission + argument hints before execution).
Sunset.CommandUsage = {
    kick = { usage = '/kick [server id] [reason]', minArgs = 1 },
    ban = { usage = '/ban [server id] [reason]', minArgs = 1 },
    unban = { usage = '/unban [player id or license:xxx]', minArgs = 1 },
    tp = { usage = '/tp [server id] or /tp [x] [y] [z]', minArgs = 1 },
    bring = { usage = '/bring [server id]', minArgs = 1 },
    car = { usage = '/car [model]', minArgs = 0 },
    dv = { usage = '/dv', minArgs = 0 },
    heal = { usage = '/heal [server id]', minArgs = 0 },
    revive = { usage = '/revive [server id]', minArgs = 0 },
    arespawn = { usage = '/arespawn [server id] | hospital | menu', minArgs = 1 },
    noclip = { usage = '/noclip', minArgs = 0 },
    god = { usage = '/god', minArgs = 0 },
    anno = { usage = '/anno [text]', minArgs = 1 },
    cc = { usage = '/cc — clear everyone\'s chat (staff 2+)', minArgs = 0 },
    setadmin = { usage = '/setadmin [username or id] [level 0-5]', minArgs = 2 },
    coords = { usage = '/coords [v4]', minArgs = 0 },
    dl = { usage = '/dl — toggle nearby vehicle debug labels (staff 2+)', minArgs = 0 },
    moveveh = { usage = '/moveveh — 3D free move/rotate vehicle/trailer gizmo (admin 1+)', minArgs = 0 },
    vehfree = { usage = '/vehfree — 3D free move/rotate vehicle/trailer gizmo (admin 1+)', minArgs = 0 },
    spawntrailer = { usage = '/spawntrailer [tanker|trailers|tr2...] — spawn trailer & start 3D positioner (admin 1+)', minArgs = 0 },
    tptruck = { usage = '/tptruck [wp|1-5|pickup|delivery|depot] — teleport truck & trailer safely', minArgs = 0 },
    trucktp = { usage = '/trucktp [wp|1-5|pickup|delivery|depot] — teleport truck & trailer safely', minArgs = 0 },
    hudexport = { usage = '/hudexport', minArgs = 0 },
    setcp = { usage = '/setcp [name]', minArgs = 1 },
    delcp = { usage = '/delcp [name]', minArgs = 1 },
    gotocp = { usage = '/gotocp [name]', minArgs = 1 },
    gotoloc = { usage = '/gotoloc [location id or name]', minArgs = 1 },
    speed = { usage = '/speed [multiplier]', minArgs = 1 },
    dealershipadmin = { usage = '/dealershipadmin', minArgs = 0 },
    setjob = { usage = '/setjob [server id] [job]', minArgs = 2 },
    setfaction = { usage = '/setfaction [server id] [faction] [grade]', minArgs = 2 },
    givecar = { usage = '/givecar [server id] [model]', minArgs = 2 },
    giveitem = { usage = '/giveitem [server id] [item] [count]', minArgs = 2 },
    givegun = { usage = '/givegun [server id] [weapon] [ammo]', minArgs = 2 },
    setleader = { usage = '/setleader [server id] [faction]', minArgs = 2 },
    removeleader = { usage = '/removeleader [server id] [faction]', minArgs = 2 },
    acreatehouse = { usage = '/acreatehouse [pret] [interior] [nivel minim] [nume]', minArgs = 4 },
    ahouseedit = { usage = '/ahouseedit [house id] [field] [value]', minArgs = 3 },
    astats = { usage = '/astats [server id]', minArgs = 1 },
    setstat = { usage = '/setstat [server id] [stat] [value]', minArgs = 3 },
    setrob = { usage = '/setrob [server id] [value]', minArgs = 2 },
    setjobstat = { usage = '/setjobstat [server id] [job] [stat] [value]', minArgs = 4 },
    givelicense = { usage = '/givelicense [server id] [driver|pilot|boat|weapon|hunting]', minArgs = 2 },
    agivelicense = { usage = '/agivelicense [server id] [driver|pilot|boat|weapon|hunting]', minArgs = 2 },
    revokelicense = { usage = '/revokelicense [server id] [driver|pilot|boat|weapon|hunting]', minArgs = 2 },
    achecklicenses = { usage = '/achecklicenses [server id]', minArgs = 1 },
    issuelicense = { usage = '/issuelicense [server id] [pilot|boat|weapon|hunting]', minArgs = 2 },
    lssireviews = { usage = '/lssireviews [pending|all]', minArgs = 0 },
    lssireport = { usage = '/lssireport [report id]', minArgs = 1 },
    lssireview = { usage = '/lssireview [report id] [mistakes: 0, 0.5, 1...] [approved|improve] [notes]', minArgs = 4 },
    lssiperformance = { usage = '/lssiperformance [server id]', minArgs = 0 },
    lssimark = { usage = '/lssimark [candidate id] [0.5|1] [observed mistake]', minArgs = 3 },
    lssiunmark = { usage = '/lssiunmark [candidate id]', minArgs = 1 },
    issuelicense = { usage = '/issuelicense [player id] [pilot|boat|weapon|hunting] — LSSI instructor on duty only', minArgs = 2 },
    me = { usage = '/me [action text]', minArgs = 1 },
    ['do'] = { usage = '/do [scene text]', minArgs = 1 },
    gov = { usage = '/gov [announcement]', minArgs = 1 },
    f = { usage = '/f [message]', minArgs = 1 },
    r = { usage = '/r [message]', minArgs = 1 },
    d = { usage = '/d [message]', minArgs = 1 },
    m = { usage = '/m [message]', minArgs = 1 },
    c = { usage = '/c [message]', minArgs = 1 },
    su = { usage = '/su [id] [reason_code]', minArgs = 0 },
    startradar = { usage = '/startradar [limit_kmh]', minArgs = 0 },
    help = { usage = '/help', minArgs = 0 },
    stats = { usage = '/stats', minArgs = 0 },
    buylevel = { usage = '/buylevel', minArgs = 0 },
    inventory = { usage = '/inventory', minArgs = 0 },
    phone = { usage = '/phone', minArgs = 0 },
    v = { usage = '/v', minArgs = 0 },
    garage = { usage = '/garage', minArgs = 0 },
    park = { usage = '/park', minArgs = 0 },
    properties = { usage = '/properties', minArgs = 0 },
    emotes = { usage = '/emotes', minArgs = 0 },
    emote = { usage = '/emote [emote name]', minArgs = 1 },
    anim = { usage = '/anim [emote name]', minArgs = 1 },
    e = { usage = '/e [mesaj] (staff chat)', minArgs = 1 },
    stopemote = { usage = '/stopemote', minArgs = 0 },
    pass = { usage = '/pass', minArgs = 0 },
    missions = { usage = '/missions', minArgs = 0 },
    duty = { usage = '/duty', minArgs = 0 },
    faction = { usage = '/faction', minArgs = 0 },
    factions = { usage = '/factions', minArgs = 0 },
    finvite = { usage = '/finvite [server id]', minArgs = 1 },
    acceptfaction = { usage = '/acceptfaction', minArgs = 0 },
    declinefaction = { usage = '/declinefaction', minArgs = 0 },
    clan = { usage = '/clan', minArgs = 0 },
    clans = { usage = '/clans', minArgs = 0 },
    acceptclan = { usage = '/acceptclan', minArgs = 0 },
    declineclan = { usage = '/declineclan', minArgs = 0 },
    dealership = { usage = '/dealership', minArgs = 0 },
    relook = { usage = '/relook', minArgs = 0 },
    skins = { usage = '/skins — open wardrobe to equip owned skins', minArgs = 0 },
    myskins = { usage = '/myskins — open wardrobe to equip owned skins', minArgs = 0 },
    hudedit = { usage = '/hudedit', minArgs = 0 },
    hudreset = { usage = '/hudreset', minArgs = 0 },
    rob = { usage = '/rob', minArgs = 0 },
    getpos = { usage = '/getpos', minArgs = 0 },
    pos = { usage = '/pos', minArgs = 0 },
    biz = { usage = '/biz [admin|help] — owner panel; /biz admin for staff settings', minArgs = 0 },
    abiz = { usage = '/abiz — admin business panel (staff level 3+)', minArgs = 0 },
    bizadmin = { usage = '/bizadmin — admin business panel (staff level 3+)', minArgs = 0 },
    bizhelp = { usage = '/bizhelp — list business commands', minArgs = 0 },
    ecudebug = { usage = '/ecudebug — ECU diagnostics (in vehicle, admin 2+)', minArgs = 0 },
    fnc = { usage = '/fnc [id] [reason/new_name] — force a name change for a player (admin)', minArgs = 1 },
    forcenamechange = { usage = '/forcenamechange [id] [reason/new_name] — force a name change (admin)', minArgs = 1 },
    -- [SUGGESTIONS] player-facing commands that had no usage entry (invisible
    -- in the chat suggestion list until now).
    ['112'] = { usage = '/112 — open the emergency call menu', minArgs = 0 },
    acceptfare = { usage = '/acceptfare — accept a taxi ride offer', minArgs = 0 },
    declinefare = { usage = '/declinefare — decline a taxi ride offer', minArgs = 0 },
    battlepass = { usage = '/battlepass — open the Blaze Pass panel', minArgs = 0 },
    lock = { usage = '/lock — lock/unlock your vehicle', minArgs = 0 },
    proximity = { usage = '/proximity — set voice proximity range', minArgs = 0 },
    trunk = { usage = '/trunk [put|take] [item] [count] — vehicle trunk', minArgs = 0 },
    glovebox = { usage = '/glovebox [put|take] [item] [count] — vehicle glovebox', minArgs = 0 },
    blzresmon = { usage = '/blzresmon [seconds] — per-player resmon sample (admin 3+)', minArgs = 0 },
    spy = { usage = '/spy — admin 3+: see faction /f /r /d traffic', minArgs = 0 },
    sweeporphans = { usage = '/sweeporphans [force] — admin 3+: report/delete orphaned entities', minArgs = 0 },
    inspect = { usage = '/inspect — admin 3+: laser entity inspector', minArgs = 0 },
    cinematic = { usage = '/cinematic — admin 3+: cinematic camera snapshots', minArgs = 0 },
    intervene = { usage = '/intervene — rank 5+: claim an unowned turf being captured', minArgs = 0 },
    armory = { usage = '/armory — war loadout menu (during a war)', minArgs = 0 },
    armurie = { usage = '/armurie — alias for /armory', minArgs = 0 },
    turfs = { usage = '/turfs — open the interactive gang turf polygon map', minArgs = 0 },
    attackturf = { usage = '/attackturf — rank 5+: attack the turf you stand in', minArgs = 0 },
    ad = { usage = '/ad [text] — submit an advertisement at a CNN location ($500)', minArgs = 1 },
    myad = { usage = '/myad — check the queue status and ETA of your active CNN ad', minArgs = 0 },
    ads = { usage = '/ads — view pending CNN advertisement queue (staff)', minArgs = 0 },
    adlist = { usage = '/adlist — alias for /ads', minArgs = 0 },
    acceptad = { usage = '/acceptad [id] — approve a pending CNN ad (staff)', minArgs = 1 },
    aad = { usage = '/aad [id] — alias for /acceptad', minArgs = 1 },
    deletead = { usage = '/deletead [id] [reason] — reject/cancel a pending CNN ad (staff)', minArgs = 1 },
    dad = { usage = '/dad [id] [reason] — alias for /deletead', minArgs = 1 },
    rejectad = { usage = '/rejectad [id] [reason] — reject a pending CNN ad (staff)', minArgs = 1 },
    admute = { usage = '/admute [player id] [minutes] [reason] — block a player from posting CNN ads (staff)', minArgs = 3 },
    loto = { usage = '/loto [1-100|info] — buy an hourly lottery ticket', minArgs = 0 },
    lottery = { usage = '/lottery — alias for /loto', minArgs = 0 },
    barbut = { usage = '/barbut [id|accept|decline] [bet] — dice game (min $100)', minArgs = 0 },
    dice = { usage = '/dice — alias for /barbut', minArgs = 0 },
    acheat = { usage = '/acheat [server id] — anticheat heat list / player tick detail (staff)', minArgs = 0 },
    achud = { usage = '/achud — toggle the on-screen Blaze Shield widget (staff)', minArgs = 0 },
    helpdesk = { usage = '/helpdesk — staff console: roster, heat, reports, quick actions (staff)', minArgs = 0 },
    aduty = { usage = '/aduty — toggle on-duty staff mode with visible [HELPER] chat prefix', minArgs = 0 },
    a = { usage = '/a [message] — staff chat (visible to all online staff)', minArgs = 1 },
    impound = { usage = '/impound [reason] — confiscate a nearby vehicle (law enforcement)', minArgs = 0 },
    -- [ADMIN SYSTEM] sanctions + presence tools (levels in SunsetAdmin.Commands)
    warn = { usage = '/warn [server id] [reason] — official warning (staff 1+)', minArgs = 2 },
    history = { usage = '/history [server id] — sanction history (staff 1+)', minArgs = 1 },
    clearwarns = { usage = '/clearwarns [server id] — clear warn history (staff 3+)', minArgs = 1 },
    freeze = { usage = '/freeze [server id] — immobilize a player (staff 1+)', minArgs = 1 },
    unfreeze = { usage = '/unfreeze [server id] — release a frozen player (staff 1+)', minArgs = 1 },
    pullout = { usage = '/pullout [server id] — extract a player from their vehicle (staff 1+)', minArgs = 1 },
    spectate = { usage = '/spectate [server id|off] — invisibly watch a player (staff 2+)', minArgs = 1 },
    slap = { usage = '/slap [server id] — launch a player (staff 2+)', minArgs = 1 },
    tpcar = { usage = '/tpcar [server id] — teleport to a player WITH your vehicle (staff 2+)', minArgs = 1 },
    bringcar = { usage = '/bringcar [server id] — bring a player AND their vehicle to you (staff 2+)', minArgs = 1 },
    tpback = { usage = '/tpback — restore your routing bucket after spectate/tpcar into a property (staff 2+)', minArgs = 0 },
    ajail = { usage = '/ajail [server id] [minutes 1-1440] [reason] — admin jail (staff 2+)', minArgs = 2 },
    aunjail = { usage = '/aunjail [server id] — release from jail (staff 2+)', minArgs = 1 },
    aclear = { usage = '/aclear [server id] — clear wanted stars (staff 2+)', minArgs = 1 },
    ahealall = { usage = '/ahealall — heal every player (staff 3+, double-tap confirm)', minArgs = 0 },
    fixall = { usage = '/fixall — repair every vehicle (staff 3+, double-tap confirm)', minArgs = 0 },
    dvall = { usage = '/dvall — delete unowned vehicles in 60m (staff 3+, double-tap confirm)', minArgs = 0 },
    gotoid = { usage = '/gotoid [server id] — alias for /tp [id] (staff 2+)', minArgs = 1 },
    setclan = { usage = '/setclan [server id] [clan id|none] [rank] — move a player between clans (staff 3+)', minArgs = 2 },
    tempban = { usage = '/tempban [server id] [30m|1h|6h|1d|7d|30d] [reason] (staff 3+)', minArgs = 3 },
    -- [SA-MP /n & /helpme] newbie question system
    n = { usage = '/n [intrebare] — adreseaza o intrebare helperilor', minArgs = 1 },
    helpme = { usage = '/helpme [intrebare] — adreseaza o intrebare helperilor', minArgs = 1 },
    na = { usage = '/na [id] [raspuns] — raspunde la intrebarea unui incepator (staff)', minArgs = 1 },
    an = { usage = '/an [id] [raspuns] — raspunde la intrebarea unui incepator (staff)', minArgs = 1 },
    nr = { usage = '/nr [id] [raspuns] — raspunde la intrebarea unui incepator (staff)', minArgs = 1 },
    nd = { usage = '/nd [id] — sterge o intrebare de incepator (staff)', minArgs = 1 },
    report = { usage = '/report [mesaj] — trimite un tichet / report catre admini', minArgs = 1 },
    cr = { usage = '/cr [server id] [motiv optional] — inchide un report sau intrebare (staff)', minArgs = 1 },
    ar = { usage = '/ar [server id] — preia un report sau intrebare (staff)', minArgs = 1 },
    reports = { usage = '/reports — vizualizeaza rapoartele active (admin)', minArgs = 0 },
    lc = { usage = '/lc [mesaj] — chat-ul liderilor si al adminilor', minArgs = 1 },
}

Sunset.HelpDispatchEntries = {
    { cmd = '/calls', desc = 'Open service calls panel (on duty)' },
    { cmd = '/servicecalls', desc = 'List open calls for your duty role' },
    { cmd = '/accept [type] [id]', desc = 'Accept a service call' },
    { cmd = '/cancel [type] [id]', desc = 'Cancel a service call' },
}

Sunset.HelpFireEntries = {
    { cmd = '/fd', desc = 'Full LSFD how-to in chat' },
    { cmd = '/firestart', desc = 'Start a vehicle fire if none is active (on duty)' },
    { cmd = '/firecalls', desc = 'List fires and set GPS to the first one' },
    { cmd = '/calls', desc = 'Accept civilian /service fire calls' },
    { cmd = 'Extinguisher', desc = 'Walk up to the burning wreck — spray LMB until it dies' },
    { cmd = '[E] garage', desc = 'Spawn the firetruk at Fire Station Garage' },
}

--- Client-registered commands (not always visible to server GetRegisteredCommands).
Sunset.ClientCommands = {}
local function markClientCommand(name)
    if name and name ~= '' then
        Sunset.ClientCommands[string.lower(name)] = true
    end
end

for _, row in ipairs(Sunset.HelpGeneralEntries or {}) do
    markClientCommand(row.cmd and row.cmd:match('^/(%w+)'))
end
for _, list in ipairs({ Sunset.HelpDispatchEntries, Sunset.HelpFireEntries }) do
    for _, row in ipairs(list or {}) do
        markClientCommand(row.cmd and row.cmd:match('^/(%w+)'))
    end
end

for _, name in ipairs({
    'noclip', 'god', 'coords', 'getpos', 'pos', 'car', 'dv', 'hudexport',
    'fine', 'cuff', 'uncuff', 'repairveh', 'fare', 'finvite', 'accept', 'fpromote',
    'fgiverank', 'funinvite', 'fwarn', 'fmotd', 'fmembers', 'cmotd', 'sellpouch', 'fence',
    'pd', 'fd', 'pdgarage', 'su', 'so', 'clear', 'unjail', 'wanted', 'find', 'arrest',
    'booking', 'backup', 'cbackup', 'mdc', 'ticket', 'confiscate', 'radars', 'startradar', 'setradar', 'radar', 'stopradar',
    'handsup', 'frisk', 'leavefaction', 'quitfaction', 'factionquit', 'quitgroup',
    'acceptfaction', 'declinefaction', 'faction', 'factions', 'crafting', 'quitjob', 'jobhelp', 'documents',
    'id', 'licenses', 'givekeys', 'takekeys', 'park', 'recovertrailer', 'service',
    'f', 'r', 'd', 'gov', 'm', 'megaphone', 'calls', 'servicecalls', 'cancel',
    'c', 'cwarn', 'cw', 'clan', 'clans', 'group', 'acceptclan', 'declineclan',
    'help', 'pass', 'missions', 'stats', 'inventory', 'accepttrade', 'declinetrade', 'phone', 'emotes', 'interact', 'interactplayer',
    'jobs', 'work', 'skills', 'fish', 'sw', 'stopwork',
    'firestart', 'firecalls', 'respawn', 'sethome', 'renthouse', 'unrent',
    'house', 'houses', 'myhouse', 'properties', 'biz', 'mybiz', 'businesses', 'mybusiness', 'abiz', 'abusiness', 'bizadmin', 'bizhelp',
    'fixnui', 'cursor',
    'stabilize', 'heal', 'revive', 'rob', 'duty', 'fw', 'v', 'garage',
    'lssireviews', 'lssireview', 'lssireport', 'lssiperformance',
    'lssimark', 'lssiunmark',
}) do
    markClientCommand(name)
end

--- Admin commands handled on the client (server validates via NetEvents).
Sunset.ClientAdminCommands = {
    setcp = true,
    delcp = true,
    gotocp = true,
    gotoloc = true,
    speed = true,
    coords = true,
    getpos = true,
    pos = true,
    dealershipadmin = true,
    hudexport = true,
}
