fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name 'sunset_core'
author 'SunsetMP'
description 'Core framework — player management, database, callbacks'
version '1.0.0'

shared_scripts {
    'shared/boot_debug.lua',
    'shared/config.lua',
    'shared/locales/en.lua',
    'shared/locales/ro.lua',
    'shared/locale.lua',
    'shared/jobs_civilian.lua',
    'shared/jobs_workplaces.lua',
    'shared/jobs_config.lua',
    'shared/profile.lua',
    'shared/faction_core.lua',
    'shared/faction_grades.lua',
    'shared/faction_outfits.lua',
    'shared/dispatch.lua',
    'shared/job_session.lua',
    'shared/factions.lua',
    'shared/crafting.lua',
    'shared/police.lua',
    'shared/utils.lua',
    'shared/items.lua',
    'shared/password.lua',
    'shared/progression_gates.lua',
    'shared/help_registry.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'server/command_feedback.lua',
    'server/discord_logs.lua',
    'server/security.lua',
    'server/main.lua',
    'server/locale_commands.lua',
    'server/money_log.lua',
    'server/player.lua',
    'server/callbacks.lua',
}

client_scripts {
    'client/boot_debug.lua',
    'client/main.lua',
    'client/callbacks.lua',
    'client/world_stream.lua',
}

exports {
    'GetPlayer',
    'GetCharacter',
    'IsPlayerReady',
    'AwaitGameReady',
    'RequestModelSafe',
    'CreateSafeBlip',
    'TriggerCallback',
    'BootLog',
    'BootLogVerbose',
    'GetBootId',
    'GetLocale',
    'Translate',
    'IsValidLocale',
    'SetLocale',
    'RecordMilestone',
    'RecordHitch',
    'CanAccess',
}

server_exports {
    'GetPlayer',
    'GetCharacter',
    'GetPlayerDisplayName',
    'GetPlayerBaseName',
    'GetPlayerLocale',
    'SetConnectionLocale',
    'SetPlayerLocale',
    'TFor',
    'NotifyFor',
    'BroadcastLocalized',
    'RegisterCallback',
    'SaveCharacter',
    'GetMoneyHistory',
    'LogMoneyTransaction',
    'SendDiscordLog',
    'AddMoney',
    'RefreshMoney',
    'DebitMoneyInTransaction',
    'CreditMoneyInTransaction',
    'AddMoneyToCharacter',
    'RemoveMoney',
    'MoveMoney',
    'TransferMoney',
    'GetMoney',
    'SetPersistentStat',
    'RefreshBlazePoints',
    'SpendBlazePoints',
    'AddBlazePoints',
    'RenameCharacter',
    'SetHomeProperty',
    'SetJob',
    'SetFaction',
    'SetFactionByCharacterId',
    'AddXP',
    'AddRespectPoints',
    'GrantRespect',
    'GetRobPoints',
    'IsIncapacitated',
    'SetRobPoints',
    'AddRobPoints',
    'GetSpawnPosition',
    'SetSpawnPreference',
    'ExecutePlayerCommand',
    'CompleteAuthentication',
    'CommandReply',
    'CommandDenyAdmin',
    'CommandDenyHeal',
    'CommandDenyRevive',
    'CommandPlayerNotFound',
    'CommandNoCharacter',
    'CommandUsage',
    'OnlinePlayerIds',
    'CommandListKeys',
    'CanAccess',
    'CanAccessCharacter',
}
