function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tol3j50", "J50 Concept")
    AddTextEntry("tol22m5", "Rhinehart G30")
    AddTextEntry("tol240sx", "Remus 240")
    AddTextEntry("tol675ltsp", "T20 LT Spider")
    AddTextEntry("tol700", "700R")
    AddTextEntry("tola6", "Tailgater A6")
    AddTextEntry("tolap2", "Aphelion")
    AddTextEntry("tolaudidy", "10F Concept")
    AddTextEntry("tolbt62r", "Apex R")
    AddTextEntry("tolc7", "Coquette C7")
    AddTextEntry("tolc63", "Schafter C63")
    AddTextEntry("tolcharger2", "Buffalo STX-R")
    AddTextEntry("tolcurus", "Toros S")
    AddTextEntry("toldemon", "Gauntlet Demon")
    AddTextEntry("toldurus", "Durus")
    AddTextEntry("tole36prb", "Sentinel Classic RS")
    AddTextEntry("tole36v", "Sentinel Classic Safari")
    AddTextEntry("tole6314", "Zion V10")
    AddTextEntry("tolevo9", "Kuruma IX")
    AddTextEntry("tolexor", "Vigero ZX")
    AddTextEntry("tolf8spider", "Furia Spider")
    AddTextEntry("tolf360", "Turismo 360")
    AddTextEntry("tolfxxk", "Turismo XX")
    AddTextEntry("tolgtam21", "Schlagen GT")
    AddTextEntry("tolgtr", "Elegy R35")
    AddTextEntry("tolgtrlw", "Elegy R35 Widebody")
    AddTextEntry("tolka", "Entity KR")
    AddTextEntry("tollam2", "Tempesta V10")
    AddTextEntry("tollwalk458", "Itali Widebody")
    AddTextEntry("tolm5cs22", "Rhinehart CS")
    AddTextEntry("tolm5e60", "Oracle V10")
    AddTextEntry("tolm6x6", "Dubsta 6x6")
    AddTextEntry("tolmig", "MIG GT")
    AddTextEntry("tolmm6x6", "Dubsta 6x6 Custom")
    AddTextEntry("tolmus2", "Dominator Custom")
    AddTextEntry("tolmustan", "Dominator GT")
    AddTextEntry("tolmustang", "Dominator GTX")
    AddTextEntry("tolpeigerzen", "Peiger Zen")
    AddTextEntry("tolr8c", "10F Coupe")
    AddTextEntry("tolr8v10", "10F V10")
    AddTextEntry("tolr33", "Elegy Retro R33")
    AddTextEntry("tolraid", "Raid Prototype")
    AddTextEntry("tolraptorV2", "Caracara Baja")
    AddTextEntry("tolrrmansory", "Jubilee Atelier")
    AddTextEntry("tolrs5", "Tailgater RS5")
    AddTextEntry("tolrs6", "Tailgater RS6")
    AddTextEntry("tolrs7c821", "Tailgater RS7")
    AddTextEntry("tolrsurus", "Toros RS")
    AddTextEntry("tols63amg", "Schafter S63")
end)
