function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
AddTextEntry("tol3j50", "tol3j50")
AddTextEntry("tol22m5", "tol22m5")
AddTextEntry("tol240sx", "tol240sx")
AddTextEntry("tol675ltsp", "tol675ltsp")
AddTextEntry("tol700", "tol700")
AddTextEntry("tola6", "tola6")
AddTextEntry("tolap2", "tolap2")
AddTextEntry("tolaudidy", "tolaudidy")
AddTextEntry("tolbt62r", "tolbt62r")
AddTextEntry("tolc7", "tolc7")
AddTextEntry("tolc63", "tolc63")
AddTextEntry("tolcharger2", "tolcharger2")
AddTextEntry("tolcurus", "tolcurus")
AddTextEntry("toldemon", "toldemon")
AddTextEntry("toldurus", "toldurus")
AddTextEntry("tole36prb", "tole36prb")
AddTextEntry("tole36v", "tole36v")
AddTextEntry("tole6314", "tole6314")
AddTextEntry("tolevo9", "tolevo9")
AddTextEntry("tolexor", "tolexor")
AddTextEntry("tolf8spider", "tolf8spider")
AddTextEntry("tolf360", "tolf360")
AddTextEntry("tolfxxk", "tolfxxk")
AddTextEntry("tolgtam21", "tolgtam21")
AddTextEntry("tolgtr", "tolgtr")
AddTextEntry("tolgtrlw", "tolgtrlw")
AddTextEntry("tolka", "tolka")
AddTextEntry("tollam2", "tollam2")
AddTextEntry("tollwalk458", "tollwalk458")
AddTextEntry("tolm5cs22", "tolm5cs22")
AddTextEntry("tolm5e60", "tolm5e60")
AddTextEntry("tolm6x6", "tolm6x6")
AddTextEntry("tolmig", "tolmig")
AddTextEntry("tolmm6x6", "tolmm6x6")
AddTextEntry("tolmus2", "tolmus2")
AddTextEntry("tolmustan", "tolmustan")
AddTextEntry("tolmustang", "tolmustang")
AddTextEntry("tolpeigerzen", "tolpeigerzen")
AddTextEntry("tolr8c", "tolr8c")
AddTextEntry("tolr8v10", "tolr8v10")
AddTextEntry("tolr33", "tolr33")
AddTextEntry("tolraid", "tolraid")
AddTextEntry("tolraptorV2", "tolraptorV2")
AddTextEntry("tolrrmansory", "tolrrmansory")
AddTextEntry("tolrs5", "tolrs5")
AddTextEntry("tolrs6", "tolrs6")
AddTextEntry("tolrs7c821", "tolrs7c821")
AddTextEntry("tolrsurus", "tolrsurus")
AddTextEntry("tols63amg", "tols63amg")

end)