import crypto from "crypto";

const KEY_LENGTH = 32;
const SCRYPT_OPTIONS = {
  N: 32768,
  r: 8,
  p: 1,
  maxmem: 64 * 1024 * 1024, // 64 MB
};

/**
 * Verifies a plaintext password against the Node.js scrypt encoded string
 * generated by sunset_auth/server/password.js.
 *
 * Format: $scrypt$32768$8$1$<salt_base64>$<derived_base64>
 */
export function verifyScryptPassword(password: string, encoded: string): boolean {
  if (typeof password !== "string" || typeof encoded !== "string") {
    return false;
  }

  const parts = encoded.split("$");
  if (parts.length !== 7 || parts[1] !== "scrypt") {
    return false;
  }

  const N = Number(parts[2]);
  const r = Number(parts[3]);
  const p = Number(parts[4]);

  if (N !== SCRYPT_OPTIONS.N || r !== SCRYPT_OPTIONS.r || p !== SCRYPT_OPTIONS.p) {
    return false;
  }

  try {
    const salt = Buffer.from(parts[5], "base64");
    const expected = Buffer.from(parts[6], "base64");

    if (expected.length !== KEY_LENGTH) {
      return false;
    }

    const actual = crypto.scryptSync(password, salt, expected.length, {
      N,
      r,
      p,
      maxmem: SCRYPT_OPTIONS.maxmem,
    });

    return crypto.timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

/**
 * Generates an scrypt hash compatible with sunset_auth.
 */
export function hashScryptPassword(password: string): string | null {
  if (typeof password !== "string" || !password.length) return null;
  const salt = crypto.randomBytes(16);
  const derived = crypto.scryptSync(password, salt, KEY_LENGTH, SCRYPT_OPTIONS);
  return `$scrypt$${SCRYPT_OPTIONS.N}$${SCRYPT_OPTIONS.r}$${SCRYPT_OPTIONS.p}$${salt.toString("base64")}$${derived.toString("base64")}`;
}

/**
 * Checks if a hash string is in modern scrypt format.
 */
export function isModernScrypt(hash: string | null | undefined): boolean {
  return typeof hash === "string" && hash.startsWith("$scrypt$");
}

/**
 * Generates an opaque random token for sessions and link tokens.
 */
export function generateRandomToken(bytes = 32): string {
  return crypto.randomBytes(bytes).toString("base64url");
}

/**
 * Computes SHA-256 hex digest of a token.
 */
export function hashTokenSha256(token: string): string {
  return crypto.createHash("sha256").update(String(token || ""), "utf8").digest("hex");
}

/**
 * Generates a 6-digit numeric PIN code for in-game linking.
 */
export function generateSixDigitPin(): string {
  return Math.floor(100000 + Math.random() * 900000).toString();
}
